# Trend Following Live Trading Config (prod)
portfolio:
  exchange: 'Coinbase Advanced'
  name: 'Trend Following'

run:
  start_date: '2022-04-01'
  end_date: '2025-07-31'
  use_specific_start_date: true
  signal_start_date: '2022-04-01'
  warmup_days: 300
  long_only: true
  annual_trading_days: 365
  initial_capital: 15000

universe:
  tickers:
    - BTC-USD
    - ETH-USD
    - SOL-USD
    - ADA-USD
    - AVAX-USD
  # optional:
  # - XRP-USD
  # - AAVE-USD

data:
  use_coinbase_data: true
  use_saved_files: true
  saved_file_end_date: '2025-07-31'
  price_or_returns_calc: price  # 'price' or 'returns'
  moving_avg_type: exponential  # 'simple' or 'exponential'

signals:
  moving_average:
    fast_mavg: 20
    slow_mavg: 200
    mavg_stepsize: 8
    mavg_z_score_window: 126
  donchian:
    entry_rolling_donchian_window: 56
    exit_rolling_donchian_window: 28
    use_donchian_exit_gate: false
  weighting:
    ma_crossover_signal_weight: 0.9
    donchian_signal_weight: 0.1
    weighted_signal_ewm_window: 4
  activation:
    use_activation: false
    tanh_activation_constant_dict: null
  filters:
    rolling_r2:
      rolling_r2_window: 100
      lower_r_sqr_limit: 0.45
      upper_r_sqr_limit: 0.9
      r2_smooth_window: 3
      r2_confirm_days: 0
      r2_strong_threshold: 0.75
    vol_of_vol:
      log_std_window: 14
      coef_of_variation_window: 20
      vol_of_vol_z_score_window: 126
      vol_of_vol_p_min: 0.10

risk_and_sizing:
  annualized_target_volatility: 0.55
  volatility_window: 30
  rolling_cov_window: 20
  rolling_atr_window: 20
  atr_multiplier: 2.5
  highest_high_window: 56
  rolling_sharpe_window: 50
  cash_buffer_percentage: 0.10

execution_and_costs:
  transaction_cost_est: 0.001
  passive_trade_rate: 0.05
  notional_threshold_pct: 0.10
  min_trade_notional_abs: 10
  cooldown_counter_threshold: 0
